# Generated by Django 5.2.4 on 2025-07-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('DST', 'Defense'), ('K', 'Kicker')], max_length=3)),
                ('projected_points_cbs_ppr', models.FloatField(default=0)),
                ('projected_points_cbs_std', models.FloatField(default=0)),
                ('projected_points_espn_ppr', models.FloatField(default=0)),
                ('projected_points_espn_std', models.FloatField(default=0)),
            ],
        ),
    ]
