# Generated by Django 5.2.4 on 2025-08-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='projected_points_draft_sharks_ppr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='projected_points_draft_sharks_std',
            field=models.FloatField(default=0),
        ),
    ]
