# Generated by Django 5.2.4 on 2025-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_extension', '0002_player_projected_points_draft_sharks_ppr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End')], max_length=3),
        ),
    ]
