# Generated by Django 5.2.4 on 2026-08-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_extension', '0003_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
